### ISSUE TITLE
试用过程中发现的问题

### ISSUE THREAD

**Issue by ThinkBlue1991** [pokerfaceSad/GPUMounter#2]
1.使用readme中的例子(yaml文件如下)，会出现将节点调度到非GPU宿主机上
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: tensorflow/tensorflow:1.13.2-gpu
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
      env:
       - name: NVIDIA_VISIBLE_DEVICES
         value: "none"
```
2. 如果镜像中没有`mknod`执行脚本，会出错。查看源码发现的确需要有`mknod`执行脚本，这个是不是应该在`README`中说明
3. 如果AddGPU失败，新创建的`gpu-pod-slave-* `POD会一直占用GPU资源(除非将gpu-pod删除)，是否应该设置callback?
